@startuml
title Class Design of TsunagiModule

package TsunagiModule {
  class TsunagiConnection {
    Connects Unity and Server
    +ReceivePlayerMessage(string message)
    -SendReceivedMessage(string message, State state)
    -FetchAction(State state)
  }

  class TsunagiBrain {
    Determine what the character should do
    +Dictionary<Action, UnityAction> ActionDelegates
    +void ReceiveGoal(Goal goal)
    +StartThink()
    -Action NotifyActions()
    -GoapSolver goapSolver
    -State characterState
  }

  interface TsunagiCharacter {
    +void StartThink(State state)
    +delegate ReceiveActions(Action[] actionsList)
  }

  package Goap{
    class GoapSolver {
      Solver of GOAP problem
      +Action[] Solve(State goal, State current)
      +Action[] actionPool
    }
    GoapSolver ..> State : Uses >
    GoapSolver ..> Action : Uses >
    GoapSolver "1" *-- "*" Action : Has >

    abstract State{
      Vector of State
      +State Plus(State state)
      +float[] stateVector
      +Dictionary<string, int> indexNames
    }

    abstract Action {
      +ConditionSet precondition
      +State effectVector
      +float cost
      +string name
    }
    Action "1" *-- "1" State : Has >
    Action "1" *-- "1" ConditionSet : Has >

    abstract ConditionSet{
      Set of conditions for State
      +bool IsSatisfied(State state)
      +Condition[] conditions
    }
    ConditionSet "1" *-- "*" Condition : Has >

    abstract Condition{
      +string indexName
      +float value
      +ConditionOperator operator
    }
    Condition "1" *-- "1" ConditionOperator : Has >

    enum ConditionOperator {
      +Larger
      +Smaller
      +Equal
    }
  }
}

package Client{
  class Player {
  }

  class Character {
    +action()
  }

  class ChatInput {

  }
}

@enduml